import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/navbar/Navbar";
export const metadata: Metadata = {
  title: "@cleveclayton",
  description: "Generated by create next app",
};
//test
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}

      </body>
    </html>
  );
}
